sources:
  -
    git: https://github.com/soundasleep/svntime
    before: 2 hours
    between: 2 hours
    after: 1 hour
  -
    svn: https://github.com/soundasleep/svntime
  # -
  #   git: https://github.com/soundasleep/gittime

