sources:
  -
    git: https://github.com/soundasleep/gittime

authors:
  jevon:
    - jevon.*
    - Jevon.*

categories:
  test:
    # each of these is an OR on a path matches
    - spec
  config:
    # each of these is an OR on a path matches
    - config.*yml
  docs:
    # each of these is an OR on a path matches
    - README
